### ISSUE TITLE
dependencies moved getting 404

### ISSUE THREAD

**Issue by ivanfan12345** [juju4/ansible-maxmind#2]
https://github.com/juju4/ansible-maxmind/blob/9b69eda982c5bd06c5ce488e8cf0528a6ca4c9e7/templates/update-maxmind.sh.j2#L8

**Comment by juju4** [comment]
normally, already fixed in latest master
https://github.com/juju4/ansible-maxmind/commit/2f2625d6c9161fe3815a3b40da81f164821ec3ab
